name: Checkmarx AST Scan

on: [ pull_request, workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}

permissions:
  contents: read
  pull-requests: read # Required to comment scan results on pull requests

jobs:
  cx-scan:
    name: Checkmarx AST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@dab12e5276a3025532f9723601ec38a4b7a37ed5 # main
        with:
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          additional_params: --tags phoenix --threshold "sast-critical=1;sast-high=1;sast-medium=1;sast-low=1;sca-critical=1;sca-high=1;sca-medium=1;sca-low=1;iac-security-critical=1;iac-security-high=1;iac-security-medium=1;iac-security-low=1"
