name: Delete dev releases

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to delete'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to delete'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  delete:
    name: Delete Dev Releases
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for GitHub token
      contents: write  # for deleting releases
      packages: write  # for package operations
    steps:

      - name: Delete releases and tags
        continue-on-error: true
        uses: dev-drprasad/delete-older-releases@dfbe6be2a006e9475dfcbe5b8d201f1824c2a9fe  #v0.3.4
        env:
          GITHUB_TOKEN: ${{ github.token}}
        with:
          keep_latest: 0
          delete_tag_pattern: "-${{inputs.tag}}.0"
          delete_tags: true