name: Close Jira

on:
  workflow_call:
    inputs:
      issue_number:
        description: 'GitHub issue number'
        required: true
        type: number
      repo:
        description: 'Repository full name (owner/repo)'
        required: true
        type: string

jobs:
  close_jira:
    runs-on: ubuntu-latest
    env:
      JIRA_URL: "https://checkmarx.atlassian.net"
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ env.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.AST_JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.AST_JIRA_API_TOKEN }}

      - name: Extract Jira Issue Key
        id: extract_key
        uses: actions/github-script@v4
        with:
          script: |
            const [owner, repo] = "${{ inputs.repo }}".split('/');
            const issue_number = ${{ inputs.issue_number }};
            const comments = await github.issues.listComments({ owner, repo, issue_number });

            const jiraRegex = /AST-\d{3,5}/;
            for (const comment of comments.data) {
              const match = comment.body.match(jiraRegex);
              if (match) {
                core.setOutput("jira_key", match[0]);
                return;
              }
            }
            core.setFailed("No Jira issue key found in comments.");

      - name: Get current Jira status
        id: get_status
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.AST_JIRA_USER_EMAIL }}:${{ secrets.AST_JIRA_API_TOKEN }}" \
            -X GET \
            -H "Accept: application/json" \
            "${{ env.JIRA_URL }}/rest/api/3/issue/${{ steps.extract_key.outputs.jira_key }}")

          STATUS=$(echo "$RESPONSE" | jq -r '.fields.status.name')
          echo "Current status is: $STATUS"
          echo "jira_status=$STATUS" >> $GITHUB_OUTPUT

      - name: Transition to In Progress (if needed)
        if: steps.get_status.outputs.jira_status == 'Open'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract_key.outputs.jira_key }}
          transition: "Start"

      - name: Transition to Done
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract_key.outputs.jira_key }}
          transition: "Completed and Approved"