# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: Create Pre Release Or Nightly Version
on:
  workflow_call:
    inputs:
      tag:
        description: 'Jenkins tag name'
        required: false
        type: string
        default: nightly
  workflow_dispatch:
    inputs:
      tag:
        description: 'Jenkins tag name'
        required: false
        type: string
        default: nightly
permissions:
  contents: read

jobs:
  delete:
    permissions:
      contents: write
      packages: write
    uses: jenkinsci/checkmarx-ast-scanner-plugin/.github/workflows/delete-dev-releases.yml@main
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
  
  # validate:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     should_release: ${{ steps.verify-ci-status.outputs.result == 'success' }}
  #   steps:
  #     - name: Verify CI status
  #       uses: jenkins-infra/verify-ci-status-action@7d194d0c5785a12623f350581db5243063542f90 #v1.2.2
  #       id: verify-ci-status
  #       if: inputs.tag == 'nightly'
  #       with:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         output_result: true

  release:
    runs-on:  cx-public-ubuntu-x64
    # needs: validate
    # if: ${{ inputs.tag != 'nightly' || needs.validate.outputs.should_release == 'true' }}
    steps:
      - name: Check out
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          lfs: true
      
      - name: Set up JDK 11
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88
        with:
          distribution: temurin
          java-version: 11

      - name: Configure echo mirror for dependency resolution
        run: |
          sed -i 's|</settings>|<mirrors><mirror><id>echo</id><mirrorOf>central</mirrorOf><url>https://maven.echohq.com</url></mirror></mirrors></settings>|' ~/.m2/settings.xml

     
      - name: mvn compile and package
        run: |
          mvn package -DskipTests -Dset.changelist
      
      - name: Create Release
        uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 #v2.0.6
        env:
          GITHUB_TOKEN: ${{ github.token}}
        with:
          name: ${{inputs.tag}}
          tag_name: ${{inputs.tag}}
          generate_release_notes: true
          prerelease: true
          files: target/checkmarx-ast-scanner.hpi
