# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: Create Pre Release Or Nightly Version
on:
  workflow_call:
    inputs:
      tag:
        description: 'Jenkins tag name'
        required: false
        type: string
        default: nightly
  workflow_dispatch:
    inputs:
      tag:
        description: 'Jenkins tag name'
        required: false
        type: string
        default: nightly

jobs:
  delete:
    uses: jenkinsci/checkmarx-ast-scanner-plugin/.github/workflows/delete-dev-releases.yml@main
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
  
  validate:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ (steps.verify-ci-status.outputs.result == 'success' }}
    steps:
      - name: Verify CI status
        uses: jenkins-infra/verify-ci-status-action@7d194d0c5785a12623f350581db5243063542f90 #v1.2.2
        id: verify-ci-status
        if: inputs.tag == 'nightly'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output_result: true

  release:
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ inputs.tag != 'nightly' || needs.validate.outputs.should_release == 'true' }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 11
     
      - name: mvn compile and package
        run: |
          mvn package -DskipTests -Dset.changelist
      
      - name: Create Release
        uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 #v2.0.6
        env:
          GITHUB_TOKEN: ${{ github.token}}
        with:
          name: ${{inputs.tag}}
          tag_name: ${{inputs.tag}}
          generate_release_notes: true
          prerelease: true
          files: target/checkmarx-ast-scanner.hpi
